---
- hosts: localhost
  become: yes
  vars:
    root_prefix: ''
    running_locally: true
  pre_tasks:
    - include_vars: configuration.yml
  tasks:
    - name: Install packages
      pacman:
        pkg: '{{ packages }}'

    - name: Apply configuration
      include_role:
        name: '{{ config_role }}'
      loop: '{{ roles }}'
      loop_control:
        loop_var: config_role
