---
- hosts: localhost
  vars:
    root_prefix: archlive/airootfs
    running_locally: false

  tasks:
    - name: Remove possibly existing old folders
      file:
        path: '{{ item }}'
        state: absent
      with_list:
        - '{{ playbook_dir }}/archlive'

    - name: Remove possibly existing old folders (root)
      file:
        path: '{{ item }}'
        state: absent
      with_list:
        - /tmp/archiso-tmp
      become: yes

    - name: Copy base profile
      copy:
        src: /usr/share/archiso/configs/releng/
        dest: archlive
        mode: preserve

    - name: Create cache marker file
      file:
        dest: archlive/CACHEDIR.TAG
        state: touch

    - name: Create output directory
      file:
        dest: out
        state: directory

    - name: Create cache marker file
      file:
        dest: out/CACHEDIR.TAG
        state: touch

    - name: Load configuration
      include_vars: configuration.yml

    - name: Configure packages for installation
      lineinfile:
        path: archlive/packages.x86_64
        line: '{{ item }}'
      with_items:
        - ansible  # required for installation of roles
        - git  # required for liquidprompt
        - zbar  # required for qr-wifi

    - name: Configure custom packages for installation
      lineinfile:
        path: archlive/packages.x86_64
        line: '{{ item }}'
      with_items: '{{ packages }}'

    - name: Apply configuration
      include_role:
        name: '{{ config_role }}'
      loop: '{{ roles }}'
      loop_control:
        loop_var: config_role

    - name: Build
      command: 'mkarchiso -v -w /tmp/archiso-tmp -o out archlive'
      become: yes
