#!/bin/bash

set -eu

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <iso> <target-device>"
  exit 1
fi

ISO="$1"
DEST=$2

if [[ ! -f "$ISO" ]]; then
  echo "$ISO is not present. Run ./download-and-remaster-iso first."
  exit 1
fi

if [[ ! -b "$DEST" ]]; then
  echo "Target $DEST does not exist or is not a block device."
  exit 1
fi

MOUNTS=$( mount | grep "$DEST" || true )

if [[ ! -z "$MOUNTS" ]]; then
  echo "$DEST or a partition on that device is mounted:"
  echo -n "$MOUNTS"
  exit 1
fi

CMD="dd if=$ISO of=$DEST oflag=direct bs=8M status=progress"

echo "Executing '$CMD', okay?"
echo "Press CTRL+C to cancel, ENTER continue."

read

$CMD
