#!/bin/bash

set -eu

USER=$(whoami)

if [[ "$USER" == "root" ]]; then
    echo "Run as regular user. This script already contains a sudo command"
    exit 1
fi

sudo ansible-playbook --become-user "$USER" download_and_remaster_iso.yml
