---
- hosts: localhost
  connection: local

  vars:
    console_foreground_color: dddddd
    locale: en_DK.UTF-8

  pre_tasks:
    - name: iso pre
      include: iso_pre.yml

    - name: pacman pre
      include: pacman_pre.yml

  roles:
    - console
    - locale
    - dotfiles
    - liquidprompt
    - use-bash
    - packages
    - qr-wifi
    - motd
    - colorschemes

  post_tasks:
    - name: pacman post
      include: pacman_post.yml

    - name: iso post
      include: iso_post.yml
