---
- name: create directories
  file:
    dest: 'rootfs_files/root/.{{ item }}'
    state: directory
  with_items:
    - elinks

- name: copy dotfiles
  copy:
    src: '{{ item }}'
    dest: 'rootfs_files/root/.{{ item }}'
  with_items:
    - bashrc
    - vimrc
    - elinks/elinks.conf
