---
- name: create directories
  file:
    dest: '{{ root_prefix }}/root/.{{ item }}'
    state: directory
  with_list:
    - bashrc.d
    - elinks
    - stuff

- name: copy dotfiles
  copy:
    src: '{{ item }}'
    dest: '{{ root_prefix }}/root/.{{ item }}'
  with_list:
    - bashrc
    - bash_profile
    - bashrc.d/aliases.bash
    - vimrc
    - elinks/elinks.conf
