---
- name: create directories
  file:
    dest: '/root/.{{ item }}'
    state: directory
  with_items:
    - bashrc.d
    - elinks
    - stuff

- name: copy dotfiles
  copy:
    src: '{{ item }}'
    dest: '/root/.{{ item }}'
  with_items:
    - bashrc
    - bashrc.d/aliases.bash
    - vimrc
    - elinks/elinks.conf
