#!/usr/bin/perl

use v5.26;
use autodie;

sub run {
    system(@_) == 0 or die "system @_ failed: $?"
}

run('pacman-key --init');
run('pacman-key --populate archlinux');


run('pacman -Sy --noconfirm ' . join(' ', @ARGV));

open(my $fh, '>', '/pkglist.txt');

my @packages = qx(pacman -Sl);
for my $line (@packages) {
    if ($line =~ /^(\S+) (\S+) (\S+) \[installed\]$/) {
        $fh->print("$1/$2-$3\n");
    } elsif ($line =~ /^(\S+) (\S+) (\S+) \[installed: (\S+)\]$/) {
        $fh->print("$1/$2-$4\n");
    }
}

$fh->close;

run('pacman -Scc --noconfirm');
